
package com.mycompany.car_showroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class LOG extends javax.swing.JFrame {

    public long ID11;
     public long IDD;
     public LOG(long a)
     {
         initComponents();
         ID11 = a;
         ID_text.setText(String.valueOf(a));

     }
    public LOG() {
        initComponents();
        manag_select.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Login_button = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        signup_button = new javax.swing.JButton();
        manag_select = new javax.swing.JRadioButton();
        cust_select = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        ID_text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        EROORS = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        Show = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 255, 255));

        jPanel7.setBackground(new java.awt.Color(16, 24, 32));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("User ID");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Password :");

        Login_button.setBackground(new java.awt.Color(0, 204, 204));
        Login_button.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Login_button.setForeground(new java.awt.Color(255, 255, 255));
        Login_button.setText("LOGIN");
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_buttonLogin_buttonActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\imamm\\OneDrive\\Desktop\\imam_old projects\\Car_showroom\\src\\main\\java\\com\\mycompany\\car_showroom\\Student-id_35758.png")); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\imamm\\OneDrive\\Desktop\\imam_old projects\\Car_showroom\\src\\main\\java\\com\\mycompany\\car_showroom\\1458264596_authorisation_lock_padlock_safe_password_privacy_security_icon-icons.com_55333.png")); // NOI18N

        signup_button.setBackground(new java.awt.Color(16, 24, 32));
        signup_button.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        signup_button.setForeground(new java.awt.Color(255, 255, 255));
        signup_button.setText("SIGNUP");
        signup_button.setBorder(null);
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonsignup_buttonActionPerformed(evt);
            }
        });

        manag_select.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        manag_select.setForeground(new java.awt.Color(255, 255, 255));
        manag_select.setText("MANAGER");
        manag_select.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                manag_selectmanag_selectStateChanged(evt);
            }
        });
        manag_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manag_selectmanag_selectActionPerformed(evt);
            }
        });

        cust_select.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cust_select.setForeground(new java.awt.Color(255, 255, 255));
        cust_select.setText("CUSTOMER");
        cust_select.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cust_selectcust_selectStateChanged(evt);
            }
        });
        cust_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_selectcust_selectActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\imamm\\OneDrive\\Desktop\\imam_old projects\\Car_showroom\\src\\main\\java\\com\\mycompany\\car_showroom\\iconfindervwlogo4140434-115963_115918.png")); // NOI18N
        jLabel4.setText("          LATEST CARS ");

        ID_text.setBackground(new java.awt.Color(16, 24, 32));
        ID_text.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        ID_text.setForeground(new java.awt.Color(0, 255, 255));
        ID_text.setBorder(null);
        ID_text.setCaretColor(new java.awt.Color(255, 255, 255));
        ID_text.setSelectedTextColor(new java.awt.Color(153, 0, 0));
        ID_text.setSelectionColor(new java.awt.Color(153, 0, 0));
        ID_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_textID_textActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(322, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(322, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        EROORS.setBackground(new java.awt.Color(16, 24, 32));
        EROORS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EROORS.setForeground(new java.awt.Color(255, 0, 0));

        password_text.setBackground(new java.awt.Color(16, 24, 32));
        password_text.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        password_text.setForeground(new java.awt.Color(0, 255, 255));
        password_text.setBorder(null);
        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });

        Show.setBackground(new java.awt.Color(16, 24, 32));
        Show.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EROORS, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(manag_select)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(password_text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Show)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cust_select)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ID_text, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(52, 52, 52)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Show))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manag_select)
                            .addComponent(cust_select)))
                    .addComponent(jLabel21))
                .addGap(9, 9, 9)
                .addComponent(EROORS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\imamm\\OneDrive\\Desktop\\imam_old projects\\Car_showroom\\src\\main\\java\\com\\mycompany\\car_showroom\\profile_user_avatar_people_icon_219228 (1).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                         WELCOME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("____________________");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("________________");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_buttonLogin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_buttonLogin_buttonActionPerformed
        IDD = Long.parseLong(ID_text.getText());

        try
        {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "c##imam", "12345");
            //______________________________________________________________________
            if(manag_select.isSelected())
            {
                String sql ="Select * from USR where SSN =? and PASS = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, ID_text.getText());
                pst.setString(2, password_text.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    
                    String sql1 ="Select * from SAL where SSN =?";
                    PreparedStatement pst1 = con.prepareStatement(sql1);
                    pst1.setString(1, ID_text.getText());
                    ResultSet rs1 = pst1.executeQuery();
                    if(rs1.next())
                    {
                        this.hide();
                        Employee M = new Employee(IDD);
                        M.show();
                    }
                    else
                    {
                        EROORS.setText("Sorry,you are a CUSTOMER.Please choose CUSTOMER button");
                    }
                }
                else
                {
                    EROORS.setText("      ID or Passwoed wrong,Please login again");
                }
            }
            //______________________________________________________________________
            else if(cust_select.isSelected())
            {
                String sql ="Select * from USR where SSN =? and PASS = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, ID_text.getText());
                pst.setString(2, password_text.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next())
                {
                    String sql1 ="Select * from CSMR where SSN =?";
                    PreparedStatement pst1 = con.prepareStatement(sql1);
                    pst1.setString(1, ID_text.getText());
                    ResultSet rs1 = pst1.executeQuery();
                    if(rs1.next())
                    {
                        this.hide();
                        Customer l=new Customer(IDD);
                        l.show();
                    }
                    else
                    {
                        EROORS.setText("Sorry,you are a MANAGER.Please choose MANAGER button");
                    }
                }
                else
                {
                    EROORS.setText("      ID or Passwoed wrong,Please login again");
                }
            }
            else
            {
                EROORS.setText("Please choose an option ");
            }
            con.close();

        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_Login_buttonLogin_buttonActionPerformed

    private void signup_buttonsignup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonsignup_buttonActionPerformed
        this.hide();
        Signup l=new Signup();
        l.show();
    }//GEN-LAST:event_signup_buttonsignup_buttonActionPerformed

    private void manag_selectmanag_selectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_manag_selectmanag_selectStateChanged

        if(manag_select.isSelected())
        {
            cust_select.setSelected(false);
        }
    }//GEN-LAST:event_manag_selectmanag_selectStateChanged

    private void manag_selectmanag_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manag_selectmanag_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manag_selectmanag_selectActionPerformed

    private void cust_selectcust_selectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cust_selectcust_selectStateChanged

        if(cust_select.isSelected())
        {
            manag_select.setSelected(false);
        }
    }//GEN-LAST:event_cust_selectcust_selectStateChanged

    private void cust_selectcust_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_selectcust_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_selectcust_selectActionPerformed

    private void ID_textID_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_textID_textActionPerformed

    }//GEN-LAST:event_ID_textID_textActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        if(Show.isSelected())
        {
            password_text.setEchoChar((char)0);        }
        else
        {
            password_text.setEchoChar('*');
        }

    }//GEN-LAST:event_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EROORS;
    private javax.swing.JTextField ID_text;
    private javax.swing.JButton Login_button;
    private javax.swing.JCheckBox Show;
    private javax.swing.JRadioButton cust_select;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton manag_select;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
